# Generated by Django 5.0.4 on 2024-10-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2e_emission', models.FloatField()),
                ('gas_name', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
    ]
