# Generated by Django 5.0.4 on 2024-10-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisiones',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
